"""empty message

Revision ID: 695605b1c61a
Revises: a96ff9e3efb6
Create Date: 2021-07-25 23:51:24.185525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695605b1c61a'
down_revision = 'a96ff9e3efb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
